package FrontEnd;

import DAOs.AreasDao;
import Models.Area;


/**
 * @author Francisco Javier Gordillo Aguilar - S22120154
 *         Alejandro Padilla Aguirre - S22120151
 */
public class AreasUD extends javax.swing.JFrame {
    
    boolean tipoDeOperacion = true;
    /**
     * Crea una instancia de Editar pero con el objetivo de guardar
     */
    public AreasUD() {
        initComponents();
        this.txtID.setEditable(false);
        this.tipoDeOperacion = true;
        this.labelOperacion.setText("Guardar");
        setLocationRelativeTo(null); // Centra la ventana
    }
    
    /**
     * Crea una instancia de Editar para editar un producto
     * @param paraEditar
     */
    public AreasUD(Area paraEditar) {
        initComponents();
        this.tipoDeOperacion = false;
        this.labelOperacion.setText("Editar");
        this.txtID.setEditable(false);
        setValores(paraEditar);
        setLocationRelativeTo(null); // Centra la ventana
    }
    
    public void setValores(Area act){
        this.txtID.setText(act.getId()+"");
        this.txtNombre.setText(act.getNombre());
        this.txtUbicacion.setText(act.getUbicacion());   
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guardar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        labelOperacion = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblID.setText("ID");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, -1));
        jPanel1.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ubicacion");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verified_10812227.png"))); // NOI18N
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalir.setBackground(new java.awt.Color(255, 204, 204));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        jPanel2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 60, 20));

        cancelar.setBackground(new java.awt.Color(255, 204, 204));
        cancelar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        jPanel2.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 20));

        labelOperacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelOperacion.setText("LABEL");
        jPanel2.add(labelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/200w (1).gif"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        mainAreas act = new mainAreas();
        act.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        String nombreN = this.txtNombre.getText();
        String ubicacionN = this.txtUbicacion.getText();
        
        if(tipoDeOperacion){
           Area nuevo = new Area(0, nombreN,ubicacionN);
           AreasDao.registrarArea(nuevo);
        }else{
           int id = Integer.parseInt(this.txtID.getText());
           Area nuevo = new Area(id, nombreN, ubicacionN);
           AreasDao.modificarArea(nuevo);
        }
        
        
        mainAreas act = new mainAreas();
        act.setVisible(true);
        dispose();
    }//GEN-LAST:event_guardarMouseClicked

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BtnSalirMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelOperacion;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
