package FrontEnd;

import Models.Producto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import DAOs.ProductosDao;

/**
 * @author Francisco Javier Gordillo Aguilar - S22120154
 *         Alejandro Padilla Aguirre - S22120151
 */
public class mainProductos extends javax.swing.JFrame {
    
    ArrayList<Producto> prodActuales;
    
    /**
     * Creates new form main
     */
    public mainProductos() {
        initComponents();
        cargarDatos();
        setLocationRelativeTo(null); // Centra la ventana
    }
    
    public void cargarDatos(){
        
        this.prodActuales = ProductosDao.buscarProductos();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        this.tablaCont.setModel(modelo);
        for(Producto prodAct : this.prodActuales){
            Object toAdd[] = new Object[]{prodAct.getId(),prodAct.getNombre()};
            modelo.addRow(toAdd);
            this.tablaCont.revalidate();
            this.tablaCont.repaint();
        }
    }
    
    private Producto buscarProd(int id){
        for(Producto x: prodActuales){
            if(x.getId()==id) return x;
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tablaCont = new javax.swing.JTable();
        Agregar = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        eliminar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAreas = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        FOndo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(102, 102, 102));

        tablaCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        scroll.setViewportView(tablaCont);
        if (tablaCont.getColumnModel().getColumnCount() > 0) {
            tablaCont.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jPanel1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 360, 150));

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-producto.png"))); // NOI18N
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-edicion.png"))); // NOI18N
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 70, 60));
        modificar.getAccessibleContext().setAccessibleName("");

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bote-de-basura.png"))); // NOI18N
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        btnAreas.setBackground(new java.awt.Color(255, 204, 204));
        btnAreas.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        btnAreas.setText("Ver Areas");
        btnAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAreasMouseClicked(evt);
            }
        });
        jPanel2.add(btnAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 20));

        btnSalir1.setBackground(new java.awt.Color(255, 204, 204));
        btnSalir1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir1MouseClicked(evt);
            }
        });
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 60, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 400, 40));

        FOndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giphy.gif"))); // NOI18N
        jPanel1.add(FOndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 550, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 0, 690, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        ProductosUD act = new ProductosUD();
        act.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        int idAEditar = Integer.parseInt(this.tablaCont.getValueAt(this.tablaCont.getSelectedRow(), 0).toString());
        ProductosUD act = new ProductosUD(buscarProd(idAEditar));
        act.setVisible(true);
        dispose();
    }//GEN-LAST:event_modificarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        int idAEditar = Integer.parseInt(this.tablaCont.getValueAt(this.tablaCont.getSelectedRow(), 0).toString());
        ProductosDao.borrarProd(buscarProd(idAEditar));
        mainProductos act = new mainProductos();
        act.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_eliminarMouseClicked

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreasMouseClicked
        mainAreas act = new mainAreas();
        act.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAreasMouseClicked

    private void btnSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalir1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel FOndo;
    private javax.swing.JButton btnAreas;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel modificar;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaCont;
    // End of variables declaration//GEN-END:variables
}
